"""add dominio previsional

Revision ID: b5983b73acf4
Revises: a1b2c3d4e5f6
Create Date: 2026-09-23 20:58:52.993975

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5983b73acf4'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('causantes',
    sa.Column('expediente', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dni', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_fallecimiento', sa.Date(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('fecha_egreso', sa.Date(), nullable=True),
    sa.Column('escalafon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo_personal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_causantes_dni'), 'causantes', ['dni'], unique=False)
    op.create_table('conceptos',
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('columna', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('formula_unidad', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('formula_importe', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('formula_unitario', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('formula_condicion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('simbolo_unidad', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decimales_unidad', sa.Integer(), nullable=False),
    sa.Column('unidad_visible', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conceptos_codigo'), 'conceptos', ['codigo'], unique=True)
    op.create_table('formulas_auxiliares',
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('formato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('formula', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formulas_auxiliares_codigo'), 'formulas_auxiliares', ['codigo'], unique=True)
    op.create_table('grupos_concepto',
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_concepto_nombre'), 'grupos_concepto', ['nombre'], unique=True)
    op.create_table('parametros_historial',
    sa.Column('campo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_dato', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=True),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parametros_historial_campo'), 'parametros_historial', ['campo'], unique=False)
    op.create_table('tablas',
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('columnas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=True),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tablas_codigo'), 'tablas', ['codigo'], unique=True)
    op.create_table('beneficiarios',
    sa.Column('causante_id', sa.Integer(), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dni', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('parentesco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fecha_alta', sa.Date(), nullable=True),
    sa.Column('fecha_baja', sa.Date(), nullable=True),
    sa.Column('discapacidad', sa.Boolean(), nullable=False),
    sa.Column('art37', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['causante_id'], ['causantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficiarios_causante_id'), 'beneficiarios', ['causante_id'], unique=False)
    op.create_table('cargos_secuencia',
    sa.Column('causante_id', sa.Integer(), nullable=False),
    sa.Column('secuencia', sa.Integer(), nullable=False),
    sa.Column('clase', sa.Integer(), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=True),
    sa.Column('fecha_hasta', sa.Date(), nullable=True),
    sa.Column('responsabilidad_jerarquica', sa.Boolean(), nullable=False),
    sa.Column('recargo_servicio', sa.Boolean(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('titulo_pregrado_nivel', sa.Integer(), nullable=False),
    sa.Column('riesgo_especial', sa.Boolean(), nullable=False),
    sa.Column('zona_porcentaje', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('anios_antiguedad', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('presentismo', sa.Boolean(), nullable=False),
    sa.Column('cuerpo_apoyo', sa.Boolean(), nullable=False),
    sa.Column('adicional_seguridad', sa.Boolean(), nullable=False),
    sa.Column('eventos_especiales', sa.Boolean(), nullable=False),
    sa.Column('porcentaje_retiro', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('caracter', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jurisdiccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finalidad', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('funcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['causante_id'], ['causantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargos_secuencia_causante_id'), 'cargos_secuencia', ['causante_id'], unique=False)
    op.create_table('concepto_grupo',
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concepto_id'], ['conceptos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_concepto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grupo_id', 'concepto_id')
    )
    op.create_table('concepto_vigencias',
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('alcance', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('tipo_beneficio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vigencia_desde', sa.Date(), nullable=True),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['concepto_id'], ['conceptos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_concepto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepto_vigencias_concepto_id'), 'concepto_vigencias', ['concepto_id'], unique=False)
    op.create_table('filas',
    sa.Column('tabla_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('valores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tabla_id'], ['tablas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filas_tabla_id'), 'filas', ['tabla_id'], unique=False)
    op.create_table('liquidaciones',
    sa.Column('causante_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=True),
    sa.Column('fecha_hasta', sa.Date(), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['causante_id'], ['causantes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liquidaciones_causante_id'), 'liquidaciones', ['causante_id'], unique=False)
    op.create_index(op.f('ix_liquidaciones_periodo'), 'liquidaciones', ['periodo'], unique=False)
    op.create_table('servicios_periodo',
    sa.Column('causante_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=True),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('computable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['causante_id'], ['causantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicios_periodo_causante_id'), 'servicios_periodo', ['causante_id'], unique=False)
    op.create_table('zonas_destino',
    sa.Column('causante_id', sa.Integer(), nullable=False),
    sa.Column('dependencia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('porcentaje_zona', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['causante_id'], ['causantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zonas_destino_causante_id'), 'zonas_destino', ['causante_id'], unique=False)
    op.create_table('recibos',
    sa.Column('liquidacion_id', sa.Integer(), nullable=False),
    sa.Column('beneficiario_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('total_remunerativo', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_no_remunerativo', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_descuento', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_contribucion', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('sueldo_bruto', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('sueldo_neto', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['beneficiarios.id'], ),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recibos_liquidacion_id'), 'recibos', ['liquidacion_id'], unique=False)
    op.create_table('tramos_retroactivos',
    sa.Column('liquidacion_id', sa.Integer(), nullable=False),
    sa.Column('beneficiario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=False),
    sa.Column('haber_mensual', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('meses', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('importe', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('sac', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['beneficiarios.id'], ),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tramos_retroactivos_liquidacion_id'), 'tramos_retroactivos', ['liquidacion_id'], unique=False)
    op.create_table('recibo_conceptos',
    sa.Column('recibo_id', sa.Integer(), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('columna', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unidad', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('importe', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('condicion', sa.Boolean(), nullable=True),
    sa.Column('warning', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Boolean(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['concepto_id'], ['conceptos.id'], ),
    sa.ForeignKeyConstraint(['recibo_id'], ['recibos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recibo_conceptos_recibo_id'), 'recibo_conceptos', ['recibo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recibo_conceptos_recibo_id'), table_name='recibo_conceptos')
    op.drop_table('recibo_conceptos')
    op.drop_index(op.f('ix_tramos_retroactivos_liquidacion_id'), table_name='tramos_retroactivos')
    op.drop_table('tramos_retroactivos')
    op.drop_index(op.f('ix_recibos_liquidacion_id'), table_name='recibos')
    op.drop_table('recibos')
    op.drop_index(op.f('ix_zonas_destino_causante_id'), table_name='zonas_destino')
    op.drop_table('zonas_destino')
    op.drop_index(op.f('ix_servicios_periodo_causante_id'), table_name='servicios_periodo')
    op.drop_table('servicios_periodo')
    op.drop_index(op.f('ix_liquidaciones_periodo'), table_name='liquidaciones')
    op.drop_index(op.f('ix_liquidaciones_causante_id'), table_name='liquidaciones')
    op.drop_table('liquidaciones')
    op.drop_index(op.f('ix_filas_tabla_id'), table_name='filas')
    op.drop_table('filas')
    op.drop_index(op.f('ix_concepto_vigencias_concepto_id'), table_name='concepto_vigencias')
    op.drop_table('concepto_vigencias')
    op.drop_table('concepto_grupo')
    op.drop_index(op.f('ix_cargos_secuencia_causante_id'), table_name='cargos_secuencia')
    op.drop_table('cargos_secuencia')
    op.drop_index(op.f('ix_beneficiarios_causante_id'), table_name='beneficiarios')
    op.drop_table('beneficiarios')
    op.drop_index(op.f('ix_tablas_codigo'), table_name='tablas')
    op.drop_table('tablas')
    op.drop_index(op.f('ix_parametros_historial_campo'), table_name='parametros_historial')
    op.drop_table('parametros_historial')
    op.drop_index(op.f('ix_grupos_concepto_nombre'), table_name='grupos_concepto')
    op.drop_table('grupos_concepto')
    op.drop_index(op.f('ix_formulas_auxiliares_codigo'), table_name='formulas_auxiliares')
    op.drop_table('formulas_auxiliares')
    op.drop_index(op.f('ix_conceptos_codigo'), table_name='conceptos')
    op.drop_table('conceptos')
    op.drop_index(op.f('ix_causantes_dni'), table_name='causantes')
    op.drop_table('causantes')
    # ### end Alembic commands ###
